#!/command/with-contenv sh

# Copy/update binaries
mkdir -p "$TYPEDAEMON_CONFIG/.typedaemon/bin"
cp -r -t "$TYPEDAEMON_CONFIG/.typedaemon/bin" "$TYPEDAEMON_MODULE"/skel/bin/*

rm "$TYPEDAEMON_CONFIG/td"
ln -s "./.typedaemon/bin/td" "$TYPEDAEMON_CONFIG/td"
chmod +x "$TYPEDAEMON_CONFIG/td"

# Pass some env vars to shells
echo "" >> /root/.bashrc
echo "export TYPEDAEMON_MODULE=$TYPEDAEMON_MODULE" >> /root/.bashrc
echo "export TYPEDAEMON_CONFIG=$TYPEDAEMON_CONFIG" >> /root/.bashrc
