#!/command/with-contenv sh

# Copy/update binaries
cp -r -t "$TYPEDAEMON_CONFIG/bin" "$TYPEDAEMON_MODULE"/skel/bin/*

# Pass some env vars to shells
echo "" > /root/.bashrc
echo "export TYPEDAEMON_MODULE=$TYPEDAEMON_MODULE" >> /root/.bashrc
echo "export TYPEDAEMON_CONFIG=$TYPEDAEMON_CONFIG" >> /root/.bashrc
